### PR TITLE
Fix event selector matching

### LINKED ISSUE #156: Incorrect method_id definition for events ABI
ABI spec stores full 32-byte event selectors in `topic0` - https://docs.soliditylang.org/en/v0.8.23/abi-spec.html#events, which is a slightly different behavior than the 4-byte selectors used for methods and errors.

Using shorter 4-byte event ids for event signature matching is error-prone and can lead to unnecessary collisions:
```
$ cast sig 'Transfer(address,address,uint256)'                              
0xddf252ad
$ cast sig 'BeckerrJon(bytes16,bytes4,bytes23,bytes16,bytes1,bytes7,bytes1)'
0xddf252ad
$ cast sig-event 'Transfer(address,address,uint256)'                        
0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
$ cast sig-event 'BeckerrJon(bytes16,bytes4,bytes23,bytes16,bytes1,bytes7,bytes1)'
0xddf252ade8bdc6f18de3868ae50ab6e67ee261b7136b3141cd791f1ad4786a79
```

At last, 4-byte `method_id` definition in `FunctionSelector` struct does not make a lot of sense for events, a full 32-byte selector would be more useful in practice.

### PR DESCRIPTION
**Pull request by k1rill-fedoseev**
Closes #156

### CODE REVIEW

File: lib/abi/function_selector.ex [hunk 1]
```diff
@@ -415,6 +415,18 @@ defmodule ABI.FunctionSelector do
...
+  defp add_event_id(selector) do
+    signature = encode(selector)
+
+    case ExKeccak.hash_256(signature) do
+      <<event_id::binary-size(32)>> ->
+        %{selector | method_id: event_id}
+
+      _ ->
+        selector
+    end
```
Comment (alisinabh) [inline lib/abi/function_selector.ex:427]: Since no extra extraction logic is required here I would say it can be even simpler.

```suggestion
      %{selector | method_id: ExKeccak.hash_256(signature)}
    end
```

**Review by alisinabh — APPROVED** [review]
I also notices that the type declared for FunctionSelector module states that the `method_id` is a `String.t` which is incorrect and should be `binary()` instead (Or event binary with specific sizes). Maybe we can also fix it in the same PR?

Other than that, Looks good to me!

**Review by ayrat555 — APPROVED** [review]
